# This is a basic workflow to help you get started with Actions

name: TELEGAM 2 META DEPLOYMENT
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Extract file with branch name
        shell: bash
        run: echo "branch=/home/ubuntu/Telegram2Meta/${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Ensure Diractory Exist
        run: mkdir ${{ steps.extract_branch.outputs.branch }}
        continue-on-error: true

        
      - name: STOP server and Copy Files
        run: cp ./* -r ${{ steps.extract_branch.outputs.branch }} && cd ${{ steps.extract_branch.outputs.branch }} && npm i && ./node_modules/.bin/pm2 install typescript && ./node_modules/.bin/pm2 reload ecosystem.config.js
      # Runs a set of commands using the runners shell
      - name: Copying files to Folder
        run: echo ${{ steps.extract_branch.outputs.branch }}
      - name: Work Done.
        run: echo Work Done.
